:imagesdir: img

=	Порядок заполнения документа

Для корректного заполнения документа необходимо создать файл *main.adoc* следующего содержания:

[c++]
----
:my-title: Название документа    //Заполняется разработчиком
:my-subtitle: Подзаглавие        //Заполняется разработчиком
:city-date: Минск 2019           //Заполняется разработчиком
= {my-title}: {my-subtitle}          //Остается без изменений
:notitle:                        //Остается без изменений
:date: 29.04.2019                //Заполняется разработчиком (дата создания документа)
:version: 0.0.1                  //Заполняется разработчиком
:author_name: Семашко Алексей    //Заполняется разработчиком
:lang: ru                        // ru/en - зависит от языка докмента
:front-cover-image: title.pdf        //Остается без изменений
:parametres_path: resources/themes/parametres/{lang}    //Остается без изменений
include::{parametres_path}/parametres.adoc[lines1..34]  //Остается без изменений
include::{parametres_path}/author.adoc[]                //Остается без изменений

----

Далее следует заполнение документа заполнение документа. Чтобы не перегружать файл *main.adoc*,
предлагается использовать вспомогательные файлы при помощи директивы *#include*, для этого предлагается
создать в томже каталоге, в котором находится файл *main.adoc* каталог *includes* (для хранения включаемых
файлов), в котором в свою очередь нужно создать каталог *img* для хранения изображений.
Эти папки в месте с файлом *main.adoc* поместить в каталог, который мы получили после распаковки архива.
Если данные каталоги уже существуют, можно просто очистить их содержимое и поместить в них
свои файлы.

Подключение файлов к файлу *main.adoc* имеет вид:

----
include::path/to/file/including.adoc[leveloffset=+1]

где
include::         //директива препроцессора
path/to/file/     //путь к файлу
including.adoc    //название файла
[leveloffset=+1]  //смещение уровня (для присвоение каждой главе заголовка первого уровня)

`если файл *main.adoc* находится в тойже папке, что и каталог *includes* подключение будет иметь вид` +

include::includes/including.adoc[leveloffset=+1]

----

Кажлдый новый файл следуе начинать с указания пути к включаемым файлам кода и изображений:

----
:imagesdir: img  //Указание пути к изображениям
----

Далее следуют таблица "Версия документа", в ней всё, что заключена в {} скобки
  оставляем без изменений.
----

== {version-doc}

[cols="3,4,4,10a", options="header"]
|===
| {version-tab}     | {date-tab}   | {author-tab}   | {amendment-tab}
.<| {version}     .<| {date}     .<| {author}     .<| {date}
|===

----

<<<<
